name: Deploy to Vultr

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'  # 使用 Node.js 22 版本

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VULTR_MMOSERVER }}

      - name: Deploy code to Vultr
        run: |
          ssh -o StrictHostKeyChecking=no -v root@167.179.80.239 '
            if [ ! -d /web-mmo/.git ]; then
              git clone git@github.com:cyanliin/web-mmo.git /web-mmo;  
            fi &&
            cd /web-mmo &&
            git pull &&
            cd server &&
            npm install &&
            npm install -g pm2 &&  # 安裝 pm2
            pm2 restart server || pm2 start /web-mmo/server/server.js --name server'
            pm2 restart client || pm2 start npm --name client -- run dev --cwd ~/web-mmo/client'

      
