name: Deploy to Vultr

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # 使用 Node.js 19 版本

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VULTR_MMOSERVER }}

      - name: Deploy code to Vultr
        run: |
          ssh root@167.179.80.239 '
            cd ~ &&
            git pull &&
            pnpm install &&
            pm2 restart server || pm2 start ~/web-mmo/server/server.js --name server'
